### ISSUE TITLE
Federating

### ISSUE THREAD

**Issue by Scarly-Crow** [Scarly-Crow/lamia#10]
I'm on this one, but putting it here to explain what I'm going to do - which is basically to just make a simple set of endpoints for inboxes and outboxes.

#### Implementation
- [X] webfinger implementation
- [x] http signature validation
- [x] json-ld manipulation
- [ ] some way to reliably fetch an actor
- [x] create actor
- [x] create object
- [x] create activity
- [ ] parse activity (includes following/followers, etc)
- [ ] local actor inboxes
- [ ] local actor outboxes
- [ ] local follower list
- [ ] local following list
- [ ] visibility heuristics (necessary for mastodon compatibility)

**Comment by Scarly-Cat** [comment]
I've added some more information on what needs to be implemented here. I'm on this bc I've been in the weeds of trying to grok the AP stuff for a while and I *think* I may be able to pull this off.

Not included on this list for some reason atm: tests - hahaha, I Knew i was forgetting something. I suppose that it goes without saying, though, but any tests that we do will pale in comparison to putting something out there and trying to get it to federate with something like mastodon "in the wild".

**Comment by Scarly-Cat** [comment]
I just nailed in http signatures. Basically, we're doing whatever it is that mastodon expects us to do and whatever it does itself with the hopeful goal being of federating with a mastodon instance at some hypothetical point in the future and the hopeful reasoning that everyone else is going to be stuck doing this same thing, hahha.

Now, it should be time for the fun stuff.

**Comment by Scarly-Cat** [comment]
I'm currently dying. Please, send help.

It was not time for the fun stuff.

**Comment by Ghost-in-the-Chel** [comment]
Patience.

The fun will soon commence. Eventually.  Probably. Presumably? Potentially.

After the torture, that is.
