### ISSUE TITLE
Usability features that came up

### ISSUE THREAD

**Issue by Scarly-Crow** [Scarly-Crow/lamia#24]
### This issue is just a place to post when useful features/ideas to think about come up.

* https://sunbeam.city/@socalledunitedstates/101478408941375170

```
Don't know if these are what you're looking for but:

"Pronouns" box on all profiles by default
"Would you like to caption this image?" prompt when someone tries to post an image with no caption
"Your post contains ____, would you like to add a content warning?" for unCWd posts containing certain words (such as slurs)
Option for admins to disable public follower counts
```

* https://guineapig.party/@boisdevache/101478429202742306

```
can I suggest the CW prompt also display when a post has a certain number of emoji, capital letters, or symbols? They can be hard on screenreaders.
```

* https://guineapig.party/@boisdevache/101497199090833702

```
add re: to cw's to make it clear they're not the op
```

**Comment by Ghost-in-the-Chel** [comment]
ensuring that things are screen reader friendly is a good step, along with having a high contrast theme.

**Comment by Scarly-Cat** [comment]
So, I'd like to flag that the whole "automated feed updating" thing is actually terrible for screen readers. It's basically the equivalent of drinking out of a fire hose. When I turned on the feature to read the timeline in tootdon, it was overwhelming.

I wonder if there's some way to control the deluge?

My own thought is to make updates "by pull" by default. An indicator appears, you click it, your timeline opens. I think that this makes more sense than the constant flow.

**Comment by Ghost-in-the-Chel** [comment]
I like my constant flow, though admittedly I think it's probably best as an opt-in feature, rather than a default.

**Comment by cbondurant** [comment]
I think to this extent we might wish to take a note from something like [pinafore](https://github.com/nolanlawson/pinafore) where while automated feed update's are not a thing per-sea, it does fetch new updates and prompts to show them. This is actually similar to how twitter handles updates as well. This might be what Scarly previously mentioned, if so consider my vote put down for that.

**Comment by Scarly-Cat** [comment]
I just saw this and I think it's something useful to have. I tend to always do this anyway, but it's just a self-reminder that we should keep something like this in:

https://kitty.town/@June/101547647626059651

```
#mastometa are there any good usability options for emojis? Like, making them bigger or showing alt-text all the time? I pretty much never know what an emoji is supposed to be cause they're too tiny to decipher.
```
