### ISSUE TITLE
A simple login page using something that isn't terrible

### ISSUE THREAD

**Issue by Scarly-Crow** [Scarly-Crow/lamia#6]
Basically, we need a way for users to get into the site. The login form should be a simple view that when POSTed to validates a user's password (we should use scrypt tbh).

#### Implementation Checklist

- [ ] GET /login
- [ ] Password validation located at /lamia/utilities/auth.py
- [ ] POST /login
- [ ] Display error if there is one (can use vue.js if any javascript is desired)
- [ ] Should use Starlette's auth middleware https://www.starlette.io/authentication/

**Comment by Scarly-Cat** [comment]
Actually, what I was thinking about using for this is an oauth token (stored in sessioncache) and a signed cookie, something like what was talked about here: http://www.redotheweb.com/2015/11/09/api-security.html
